### ISSUE TITLE
Delete existing Experience

### ISSUE THREAD

**Issue by DeleMike** [MLH-Fellowship/orientation-project-python-23.SUM.B.1#10]
Using a `DELETE `request for the `/resume/experience` route, delete an existing Experience using its index position as an ID. As part of this, you should write a test in `test_pytest.py` to show it works.

**Comment by DeleMike** [comment]
@demarillacizere will you work on this since you handle GET request for the experience route

**Comment by demarillacizere** [comment]
> @demarillacizere will you work on this since you handle GET request for the experience route
No problem @DeleMike

**Comment by DeleMike** [comment]
Cool! Thank you @demarillacizere! 🙌🏾
