### ISSUE TITLE
Implement API route to return all "Experiences"

### ISSUE THREAD

**Issue by DeleMike** [MLH-Fellowship/orientation-project-python-23.SUM.B.1#19]
On th`e /resume/experience` route, you should:

- [ ]  Return the Experience list when a GET request is made. The return should be in a list format.

**Comment by demarillacizere** [comment]
I'm working on it

**Comment by DeleMike** [comment]
Yeah, you are right. I was trying to copy the issues here

**Comment by DeleMike** [comment]
#32 Linked with this PR.
