### ISSUE TITLE
Edit existing Education

### ISSUE THREAD

**Issue by DeleMike** [MLH-Fellowship/orientation-project-python-23.SUM.B.1#22]
Using a `PUT `request for the `/resume/education` route, update an existing Education using its index position as an ID. As part of this, you should write a test in `test_pytest.py` to show it works.

**Comment by DeleMike** [comment]
@SuelenKarbivnychyy will you work on this issue since you worked on other routes for related to `education`.

**Comment by SuelenKarbivnychyy** [comment]
@DeleMike yes I will take that. Thanks.

**Comment by SuelenKarbivnychyy** [comment]
I'm working on it.

**Comment by DeleMike** [comment]
Lovely, thanks! 🙌🏾

**Comment by DeleMike** [comment]
Closed! 🫡
