### ISSUE TITLE
Database modeling

### ISSUE THREAD

**Issue by SuelenKarbivnychyy** [MLH-Fellowship/orientation-project-python-23.SUM.B.1#39]
Based on experience, education and skill data, model the database.

**Comment by SuelenKarbivnychyy** [comment]
I'm working in it

**Comment by DeleMike** [comment]
Great stuff and thank you. What database are we going to use? 
If we need to discuss together, we can find a good time

**Comment by SuelenKarbivnychyy** [comment]
I'm developing in Sqlite3, as Damir suggested. I have the file ready and would love to discuss it, and also talk about the Orm approach suits better, I thought about SqlAlchemy, I will message you soon to schedule a time to talk about it.
