### ISSUE TITLE
Add ChatGPT functionality to help users reword the description section of their resume 

### ISSUE THREAD

**Issue by DeleMike** [MLH-Fellowship/orientation-project-python-23.SUM.B.1#6]
Both the Experience and Education sections have description fields. Using the [OpenAI API](https://platform.openai.com/overview), create suggestions on how the description field should be updated.

In order to complete this, you'll need to collaborate with the fellows contributing to JavaScript to agree on a format for how a user can accept the ChatGPT suggestion in the client and have it replace the old description on the server.

**Comment by winstxnhdw** [comment]
I’ll take on this issue. @marcusgchan are you handling the frontend for this?

**Comment by marcusgchan** [comment]
Nope, no one is currently working on the frontend

**Comment by DeleMike** [comment]
@marcusgchan, any reason why he has to wait for the frontend to be ready?

**Comment by marcusgchan** [comment]
He can work on the backend first

**Comment by DeleMike** [comment]
Addressed at #41.
