### ISSUE TITLE
Delete existing Education

### ISSUE THREAD

**Issue by DeleMike** [MLH-Fellowship/orientation-project-python-23.SUM.B.1#9]
Using a `DELETE `request for the` /resume/education` route, delete an existing Education using its index position as an ID. As part of this, you should write a test in `test_pytest.py` to show it works.

**Comment by DeleMike** [comment]
@SuelenKarbivnychyy will you work on this issue too? It is related to `education`.

**Comment by SuelenKarbivnychyy** [comment]
@DeleMike Yes, I will take it.

**Comment by SuelenKarbivnychyy** [comment]
I'm working on it

**Comment by SuelenKarbivnychyy** [comment]
@dtemir This issue is being handling on the PR #5. Please review
[https://github.com/MLH-Fellowship/orientation-project-python-23.SUM.B.1/pull/35](url)

**Comment by DeleMike** [comment]
Done at #35
